config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

post "/archive_user", to: "users#archive_user"

      resources :eyeshadows, only: [:index, :show] do
        resources :reviews, only: [:create, :show, :new]
      end
      resources :lipsticks, only: [:index, :show] do
        resources :reviews, only: [:create, :show, :new]
      end

      resources :mascaras, only: [:index, :show] do
        resources :reviews, only: [:create, :show, :new]
      end

      resources :reviews, only: [:index, :show, :create]


      devise_for :users
      resources :users, only: [:show]
      scope "/admin" do
        resources :users, only: [:index]
        resources :reviews, only: [:index]
        end
      end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eyeshadow.rb
class Eyeshadow < ApplicationRecord
  validates :name, presence: true
  has_many :reviews
end

app/models/lipstick.rb
class Lipstick < ApplicationRecord
  validates :name, presence: true
  has_many :reviews
end

app/models/mascara.rb
class Mascara < ApplicationRecord
  validates :name, presence: true
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  RATINGS = [
    [1, "❤️"],
    [2, "❤️❤️"],
    [3, "❤️❤️❤️"],
    [4, "❤️❤️❤️❤️"],
    [5, "❤️❤️❤️❤️❤️"]
  ]

  validates :rating, presence: true, numericality: true, inclusion: { in: 1..5 }
  belongs_to :user
  belongs_to :eyeshadow, optional: true
  belongs_to :lipstick, optional: true
  belongs_to :mascara, optional: true 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true,
  format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i },
  uniqueness: { case_sensitive: false }
  validates :password, presence: true
  validates :username, presence: true, uniqueness: true
  validates :admin, default: false

  has_many :reviews

end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/eyeshadows_controller.rb
class Api::V1::EyeshadowsController < Api::V1::BaseController

  def show
    if params[:eyeshadow_id]
    @eyeshadow = Eyeshadow.find(params[:id])
    @reviews = @eyeshadow.reviews
    respond_with @reviews, json: @reviews
    end
  end
  
end

app/controllers/api/v1/lipsticks_controller.rb
class Api::V1::LipsticksController < Api::V1::BaseController

  def show
    if params[:lipstick_id]
    @lipstick = lipstick.find(params[:id])
    @reviews = @lipstick.reviews
    respond_with @reviews, json: @reviews
    end
  end

end

app/controllers/api/v1/mascaras_controller.rb
class Api::V1::MascarasController < Api::V1::BaseController

  def show
    if params[:mascara_id]
    @mascara = mascara.find(params[:id])
    @reviews = @mascara.reviews
    respond_with @reviews, json: @reviews
    end
  end

end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < Api::V1::BaseController

  def index
    if params[:eyeshadow_id].present?
      @eyeshadow = Eyeshadow.find(params[:eyeshadow_id])
      @reviews = @eyeshadow.reviews
      respond_with @reviews, json: @reviews
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    added_attrs = [
      :username,
      :email,
      :password,
      :admin,
      :password_confirmation,
      :remember_me,
      :avatar,
      :avatar_cache
    ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/eyeshadows_controller.rb
class EyeshadowsController < ApplicationController

  def index
    @eyeshadows = Eyeshadow.all
  end

  def show
    @eyeshadow = Eyeshadow.find(params[:id])
    @reviews = @eyeshadow.reviews
    @review = Review.new
    @rating_collection = Review::RATINGS
  end

  private

  def eyeshadow_params
    params.require(:eyeshadow).permit(
    :name,
    :brand,
    :image_url,
    :product_link,
    :description
    )
  end
end

app/controllers/lipsticks_controller.rb
class LipsticksController < ApplicationController

  def index
    @lipsticks = Lipstick.all
  end

  def show
    @lipstick = Lipstick.find(params[:id])
    @reviews = @lipstick.reviews
    @review = Review.new
    @rating_collection = Review::RATINGS
  end

  private

  def lipstick_params
    params.require(:lipstick).permit(
    :name,
    :brand,
    :image_url,
    :product_link,
    :description
    )
  end
end

app/controllers/mascaras_controller.rb
class MascarasController < ApplicationController

  def index
    @mascaras = Mascara.all
  end

  def show
    @mascara = Mascara.find(params[:id])
    @reviews = @mascara.reviews
    @review = Review.new
    @rating_collection = Review::RATINGS
  end

  private

  def mascara_params
    params.require(:mascara).permit(
    :name,
    :brand,
    :image_url,
    :product_link,
    :description
    )
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    if params[:eyeshadow_id].present?
       @eyeshadow = Eyeshadow.find(params[:eyeshadow_id])
       @user = current_user.id
       @review = Review.new
       @review.eyeshadow = @eyeshadow
       @rating_collection = Review::RATINGS
    elsif params[:lipstick_id].present?
       @lipstick = Lipstick.find(params[:lipstick_id])
       @user = current_user.id
       @review = Review.new
       @review.lipstick = @lipstick
       @rating_collection = Review::RATINGS
    else
      @mascara = Mascara.find(params[:mascara_id])
      @user = current_user.id
      @review = Review.new
      @review.mascara = @mascara
      @rating_collection = Review::RATINGS
    end
  end

 def create
   if params[:eyeshadow_id].present?
      @eyeshadow = Eyeshadow.find(params[:eyeshadow_id])
      @user = current_user
      @review = Review.new(params_strong)
      @review.eyeshadow = @eyeshadow
      @review.user = @user
      if @review.save
          flash[:notice] = "Review added successfully"
          redirect_to eyeshadow_path(@eyeshadow)
      else
          flash[:notice] = @review.errors.full_messages.to_sentence
          @reviews = @eyeshadow.reviews
          @rating_collection = Review::RATINGS
          render '/eyeshadows/show'
        end
    elsif params[:lipstick_id].present?
      @lipstick = Lipstick.find(params[:lipstick_id])
      @user = current_user
      @review = Review.new(params_strong)
      @review.lipstick = @lipstick
      @review.user = @user
      if @review.save
         flash[:notice] = "Review added successfully"
         redirect_to lipstick_path(@lipstick)
      else
        flash[:notice] = @review.errors.full_messages.to_sentence
        @reviews = @lipstick.reviews
        @rating_collection = Review::RATINGS
        render '/lipsticks/show'
      end
    else
      @mascara = Mascara.find(params[:mascara_id])
      @user = current_user
      @review = Review.new(params_strong)
      @review.mascara = @mascara
      @review.user = @user
      if @review.save
          flash[:notice] = "Review added successfully"
          redirect_to mascara_path(@mascara)
      else
        flash[:notice] = @review.errors.full_messages.to_sentence
        @reviews = @mascara.reviews
        @rating_collection = Review::RATINGS
        render '/mascaras/show'
      end
    end
  end


  private

   def params_strong
     params.require(:review).permit(
       :rating,
       :body
     )
   end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end

  def archive_user
    if current_user.admin
   @user = User.find(params[:format])
    else
   @user = User.find(current_user.id)
  end

  @user.destroy
  if current_user.admin
    flash[:notice] = "User Deleted!"
    redirect_to users_path
  else
    flash[:notice] = "Bye! Your account has been successfully cancelled.  We hope to see you again soon."
    redirect_to root_path
  end
end


  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "User Deleted!"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/eyeshadows/index.html.erb
<h1 class="list">Eyeshadows</h1>

<ul class= "eyeshadow">
  <% @eyeshadows.each do |eyeshadow| %>
    <a id=<%=eyeshadow.id%> href="/eyeshadows/<%= eyeshadow.id%>"><img src="<%= eyeshadow.image_url%>"class="eyeshadow"></a>
  <% end %>
</ul>

app/views/eyeshadows/show.html.erb
<h1 class="eyeshadow_show"><%= @eyeshadow.name.titleize %></h1>
<div class = "row">
  <div class="large-6 columns" id = "showimages">
      <img src="<%= @eyeshadow.image_url%>">
    </div>
  <div class="large-6 columns text-center" id="info">
<h2> Brand: <%= @eyeshadow.brand.titleize %></h2>
<br>
<h4 class="scroll"><%= @eyeshadow.description %></h4>
<br>
<h3><%= link_to 'More Info!', @eyeshadow.product_link %></h3>
</div>
</div>

<br>
<br>
<%= render "reviews/eyeshadow/new" %>

<h3 id="review-show">Reviews :</h3>

<ul class="review">
  <% @reviews.each do |review| %>
  <li>
    <%= review.rating %> , <%= review.body %>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "makeupkeeper" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=IM+Fell+Double+Pica:400i" />

    <div class="top-bar">
    <a class="logo" href="/">Makeup Keeper</a>
    <div class="nav">
      <% if user_signed_in? %>
        <ul class="dropdown menu" data-dropdown-menu>
          <li>
          <%= link_to current_user.email, user_path(current_user.id) %>
            <ul class="menu">
              <% if current_user.admin == true  %>
              <td><%= link_to 'View All Users', users_path, :class => 'navbar-link' %></td>
              <% end %>
              <td><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></td>
              <td><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></td>
            </ul>
          </li>
      <% else %>
    <span><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></span>
        <span><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></span>
      <% end %>
  </ul>
</div>
    </div>



  <body>

    <%= yield %>
  </body>
</html>

app/views/lipsticks/index.html.erb
<h1 class="list">Lipticks</h1>

<ul class= "lipstick">
  <% @lipsticks.each do |lipstick| %>
    <a id=<%=lipstick.id%> href="/lipsticks/<%= lipstick.id%>"><img src="<%= lipstick.image_url%>"class="lipstick"></a>
  <% end %>
</ul>

app/views/lipsticks/show.html.erb
<h1 class="lipstick_show"><%= @lipstick.name.titleize %></h1>
<div class = "row">
  <div class="large-6 columns" id = "showimages">
      <img src="<%= @lipstick.image_url%>">
    </div>
  <div class="large-6 columns text-center" id="info">
<h2> Brand: <%= @lipstick.brand.titleize %></h2>
<br>
<h4 class="scroll"><%= @lipstick.description %></h4>
<br>
<h3><%= link_to 'More Info!', @lipstick.product_link %></h3>
</div>
</div>

<br>
<br>

<%= render "reviews/lipstick/new" %>

<h3 id="review-show">Reviews :</h3>

<ul class="review">
  <% @reviews.each do |review| %>
  <li>
    <%= review.rating %> , <%= review.body %>
  </li>
  <% end %>
</ul>

app/views/mascaras/index.html.erb
<h1 class="list">Mascaras</h1>

<ul class= "mascara">
  <% @mascaras.each do |mascara| %>
    <a id=<%=mascara.id%> href="/mascaras/<%= mascara.id%>"><img src="<%= mascara.image_url%>"class="mascara"></a>
  <% end %>
</ul>

app/views/mascaras/show.html.erb
<h1 class="mascara_show"><%= @mascara.name.titleize %></h1>
<div class = "row">
  <div class="large-6 columns" id = "showimages">
      <img src="<%= @mascara.image_url%>">
    </div>
  <div class="large-6 columns text-center" id="info">
<h2> Brand: <%= @mascara.brand.titleize %></h2>
<br>
<h4 class="scroll"><%= @mascara.description %></h4>
<br>
<h3><%= link_to 'More Info!', @mascara.product_link %></h3>
</div>
</div>

<br>
<br>

<%= render "reviews/mascara/new" %>

<h3 id="review-show">Reviews :</h3>

<ul class="review">
  <% @reviews.each do |review| %>
  <li>
    <%= review.rating %> , <%= review.body %>
  </li>
  <% end %>
</ul>

app/views/reviews/eyeshadow/_new.html.erb
<%= form_for [@eyeshadow, @review] do |f| %>
<div class="review_form">
  <div class="review_buttons">
    <%= f.label(:rating, "Rating") %>
    <%= f.collection_radio_buttons(:rating, @rating_collection, :first, :last) %>
  </div>

  <div>
    <%= f.label(:body, "Comment:") %>
    <%= f.text_field(:body) %>
  </div>

  <div>
    <%= f.submit("Submit Review") %>
  </div>
</div>

<% end %>

app/views/reviews/lipstick/_new.html.erb
<%= form_for [@lipstick, @review] do |f| %>
<div class="review_form">
  <div class="review_buttons">
    <%= f.label(:rating, "Rating") %>
    <%= f.collection_radio_buttons(:rating, @rating_collection, :first, :last) %>
  </div>

  <div>
    <%= f.label(:body, "Comment:") %>
    <%= f.text_field(:body) %>
  </div>

  <div>
    <%= f.submit("Submit Review") %>
  </div>
</div>

<% end %>

app/views/reviews/mascara/_new.html.erb
<%= form_for [@mascara, @review] do |f| %>
<div class="review_form">
  <div class="review_buttons">
    <%= f.label(:rating, "Rating:") %>
    <%= f.collection_radio_buttons(:rating, @rating_collection, :first, :last) %>
  </div>

  <div>
    <%= f.label(:body, "Comment:") %>
    <%= f.text_field(:body) %>
  </div>

  <div>
    <%= f.submit("Submit Review") %>
  </div>
</div>

<% end %>

app/views/static_pages/home.html.erb
<h1 class= "mainpage"> Makeup Keeper</h1>
<div class= "row">
  <div class="small-2 large-4 columns" id="mainpage-style">
  <%= link_to 'Eyeshadows', eyeshadows_path %>
</div>
<div class="small-2 large-4 columns" id="mainpage-style">
  <%= link_to 'Lipsticks', lipsticks_path %>
</div>
<div class="small-2 large-4 columns" id="mainpage-style">
  <%= link_to 'Mascaras', mascaras_path %>
</div>
<div class="first">
<img src="<%= asset_path( 'radhika.jpg' ) %>" height="500" width="750"/>
</div>